#!/bin/bash

status=$(iwctl station wlan0 show | grep -oE "disconnected")
essid=$(iwctl station wlan0 show | grep 'Connected network' | awk '{ print $3 }')

if [ $status ] ; then
    icon="󰖪"
    text=""
    col="#575268"

else
    icon="󰖩"
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
